# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: gustavopiovesan
# "service" is the name of this project. This will also be added to your AWS resource names.
service: handle-bank-transactions

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  stage: dev
  memorySize: 256

package:
  individually: true

build:
  esbuild:
    bundle: true
    minify: true
    sourcemap: false
    exclude:
      - '@aws-sdk/*'

functions:
  api:
    handler: src/lamba.handler
    events:
      - httpApi:
          path: '*'
          method: '*'
